language: node_js
node_js:
  - '5'
before_script:
  - sleep 15
before_deploy: "git push origin master:refs/heads/master"
deploy:
  provider: azure_web_apps
  verbose: true
  on:
    all_branches: true